//
//  ArticleDetailView.swift
//  Briefly
//
//  Created by Pranay Chander on 21/01/26.
//

import SwiftUI

struct ArticleDetailView: View {
    @State var viewModel: ArticleDetailViewModel
    
    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 16) {
                
                // Hero
                if let url = viewModel.article.thumbnailURL {
                    ArticleHeroView(url: url)
                }
                
                ArticleTitleView(title: viewModel.article.title)
                
                ArticleMetaView(article: viewModel.article)
                
                ArticleSignalsView(article: viewModel.article)
                
                if let content = viewModel.article.contentPreview, !content.isEmpty {
                    ArticleContentView(content: content)
                }
                
                // AI Actions
                if viewModel.article.contentPreview?.isEmpty == false {
                    AIActionCardView {
                        viewModel.showAIActionSheet = true
                    }
                }
                
                // Read Full Article
                if let url = viewModel.article.url, let articleURL = URL(string: url) {
                    ReadFullArticleButton(url: articleURL)
                }
            }
            .padding()
        }
        .navigationTitle("Article")
        .navigationBarTitleDisplayMode(.inline)
        .toolbar {
            ToolbarItemGroup(placement: .navigationBarTrailing) {
                Button { shareArticle() } label: {
                    Image(systemName: "square.and.arrow.up")
                }
                Button { toggleBookmark() } label: {
                    Image(systemName: "bookmark")
                }
            }
        }
        .sheet(isPresented: $viewModel.showAIActionSheet) {
            AIActionsBottomSheet(onSelect: viewModel.selectAIAction(_:))
                .presentationDetents([.medium])
        }
        .navigationDestination(item: $viewModel.selectedAIAction) { action in
            AIResultView(viewModel: viewModel.makeAIResultViewModel())
        }

        .task {
            await viewModel.loadPreview()
        }
    }
    
    private func shareArticle() {
        guard let urlString = viewModel.article.url,
              let url = URL(string: urlString) else { return }

        let activity = UIActivityViewController(
            activityItems: [viewModel.article.title, url],
            applicationActivities: nil
        )
        UIApplication.shared
            .connectedScenes
            .compactMap { ($0 as? UIWindowScene)?.keyWindow }
            .first?
            .rootViewController?
            .present(activity, animated: true)
    }
    
    private func toggleBookmark() {
        // TODO: Implement
    }
}


struct ArticleContentView: View {
    let content: String
    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text(content)
                .font(.body)
                .lineSpacing(6)
            
            HStack(spacing: 4) {
                Image(systemName: "sparkles")
                    .font(.caption2)
                    .foregroundColor(.cyan)
                Text("Generated by BRU")
                    .font(.caption2)
                    .foregroundColor(.secondary)
            }
        }
        .padding(.horizontal)
    }
}
