//
//  AIAction.swift
//  Briefly
//
//  Created by Pranay Chander on 21/01/26.
//

import Foundation

enum AIAction: CaseIterable, Identifiable {
    case summary
    case tweet
    case reddit
    case linkedin
    
    var id: Self { self }
    
    // MARK: - Display
    
    var title: String {
        switch self {
        case .summary: return "TL;DR Summary"
        case .tweet: return "Generate Tweet"
        case .reddit: return "Reddit Post"
        case .linkedin: return "LinkedIn Post"
        }
    }
    
    var subtitle: String {
        switch self {
        case .summary: return "Key points in seconds"
        case .tweet: return "Short & punchy"
        case .reddit: return "Discussion-style post"
        case .linkedin: return "Professional tone"
        }
    }
    
    var icon: String {
        switch self {
        case .summary: return "text.alignleft"
        case .tweet: return "bird"
        case .reddit: return "bubble.left.and.bubble.right"
        case .linkedin: return "briefcase"
        }
    }
    
    // MARK: - AI Instructions
    
    var instructions: String {
        switch self {
            
        case .summary:
            return """
                You are BRU, a quiet news summarization engine.
                
                Write a single, compact paragraph summarizing the article.
                
                Rules:
                - Plain text only
                - One paragraph only
                - No headings, bullets, or lists
                - No introductions or conclusions
                - Do not mention that this is a summary
                - Do not use phrases like "Here is", "This article", or "In summary"
                - If content is limited, keep the paragraph short and do not add speculation
                
                Write in a neutral, journalistic tone.
                """
            
        case .tweet:
            return """
                Write a single tweet based on the article.
                
                Rules:
                - Maximum 280 characters
                - Add hashtags if applicable
                - Add emojis if applicable
                - No introductory phrases
                - Write like a human sharing news, not marketing
                
                Output only the tweet text.
                """
            
        case .reddit:
            return """
                Write a Reddit-style post based on the article.
                
                Rules:
                - Conversational and neutral
                - Encourage discussion subtly
                - No clickbait
                - No emojis
                - No headings or markdown
                - Do not mention that this was generated by AI
                
                Output plain text only.
                """
            
        case .linkedin:
            return """
                Write a professional LinkedIn post based on the article.
                
                Rules:
                - Thoughtful, calm tone
                - No emojis
                - No hashtags
                - No marketing language
                - No call-to-action like "Read more"
                
                Output a short professional paragraph.
                """
        }
    }
}
